-- Classes, audit trail and tenant RLS hardening for Supabase/PostgreSQL.
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS is_exam_class boolean NOT NULL DEFAULT false;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';

CREATE TABLE IF NOT EXISTS public.financial_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id integer REFERENCES public.schools(id) ON DELETE SET NULL,
  actor_user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
  actor_role text NOT NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS financial_audit_logs_school_created_idx ON public.financial_audit_logs (school_id, created_at DESC);

-- The browser uses Supabase only for authentication; business data goes through
-- the server with the service-role key. These policies prevent direct cross-school
-- reads or writes when an anon/authenticated token is used.
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personnel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS educo_classes_tenant ON public.classes;
CREATE POLICY educo_classes_tenant ON public.classes FOR ALL TO authenticated
  USING (school_id IN (SELECT id FROM public.schools WHERE id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer))
  WITH CHECK (school_id IN (SELECT id FROM public.schools WHERE id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer));

DROP POLICY IF EXISTS educo_fees_tenant ON public.fees;
CREATE POLICY educo_fees_tenant ON public.fees FOR ALL TO authenticated
  USING (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer)
  WITH CHECK (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer);

DROP POLICY IF EXISTS educo_payments_tenant ON public.payments;
CREATE POLICY educo_payments_tenant ON public.payments FOR ALL TO authenticated
  USING (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer)
  WITH CHECK (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer);

DROP POLICY IF EXISTS educo_transactions_tenant ON public.transactions;
CREATE POLICY educo_transactions_tenant ON public.transactions FOR ALL TO authenticated
  USING (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer)
  WITH CHECK (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer);

DROP POLICY IF EXISTS educo_personnel_tenant ON public.personnel;
CREATE POLICY educo_personnel_tenant ON public.personnel FOR ALL TO authenticated
  USING (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer)
  WITH CHECK (school_id = (auth.jwt() -> 'user_metadata' ->> 'schoolId')::integer);

DROP POLICY IF EXISTS educo_financial_audit_server_only ON public.financial_audit_logs;
CREATE POLICY educo_financial_audit_server_only ON public.financial_audit_logs FOR SELECT TO authenticated USING (false);
