-- Persistent storage for WebAuthn / passkey credentials.
-- This table is intentionally server-only: the Render API uses the Supabase
-- service-role client, while browser clients must never read public keys or
-- credential identifiers directly.
CREATE TABLE IF NOT EXISTS public.webauthn_credentials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  user_email text NOT NULL,
  credential_id text NOT NULL UNIQUE,
  public_key text NOT NULL,
  counter bigint NOT NULL DEFAULT 0,
  device_name text,
  device_type text,
  transports jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS webauthn_credentials_user_email_active_idx
  ON public.webauthn_credentials (lower(user_email))
  WHERE revoked_at IS NULL;

ALTER TABLE public.webauthn_credentials ENABLE ROW LEVEL SECURITY;

-- No authenticated/anonymous policy is created.  The Supabase service role
-- bypasses RLS and is used only by the server-side WebAuthn router.
