import React, { useMemo, useState } from 'react';
import { FileText, ShieldCheck, Clock, WalletCards, Search, UploadCloud, Send, FolderOpen } from 'lucide-react';
import { createAdministrativeApplication, submitAdministrativeApplication, uploadAdministrativeFile } from '../src/services/administrativeServices';

type Service = { code:string; ministry:string; name:string; audience:string; feeStatus:'VERIFIED_CURRENT'|'HISTORICAL'|'TO_VERIFY'|'FREE'; fee?:number; result:string; legal:string; };
const SERVICES: Service[] = [
 {code:'MES-CRE',ministry:'MES',name:"Agrément de création d'un établissement privé",audience:'Établissement / Promoteur',feeStatus:'TO_VERIFY',result:'Agrément / acte administratif',legal:'Décret n°96-221 ; textes MES'},
 {code:'MES-OUV',ministry:'MES',name:"Agrément d'ouverture d'un établissement privé",audience:'Établissement',feeStatus:'TO_VERIFY',result:'Agrément / acte administratif',legal:'Arrêté n°7061 du 8 juin 2023'},
 {code:'MES-REN-ENS',ministry:'MES',name:"Renouvellement de l'autorisation d'enseigner",audience:'Enseignant',feeStatus:'HISTORICAL',result:'Autorisation renouvelée',legal:'Référentiel financier historique 2023'},
 {code:'METP-CRE',ministry:'METP',name:"Création d'un établissement privé",audience:'Établissement / Promoteur',feeStatus:'TO_VERIFY',result:'Décision / agrément',legal:"Service des agréments du METP"},
 {code:'METP-OUV',ministry:'METP',name:"Ouverture d'un établissement privé",audience:'Établissement',feeStatus:'TO_VERIFY',result:'Décision / agrément',legal:"Service des agréments du METP"},
 {code:'METP-MOD',ministry:'METP',name:"Modification d'un établissement privé",audience:'Établissement',feeStatus:'TO_VERIFY',result:'Décision administrative',legal:"Service des agréments du METP"},
 {code:'MEPSA-AGR',ministry:'MEPSA',name:"Agrément d'un établissement privé",audience:'Établissement / Promoteur',feeStatus:'TO_VERIFY',result:'Agrément',legal:'Décret n°96-221 ; décret n°2008-127'},
 {code:'MFP-EQD',ministry:'MFP',name:"Équivalence administrative de diplôme",audience:'Particulier',feeStatus:'TO_VERIFY',result:"PV de commission / acte de classement",legal:'Procédure DGFP publiée'}
];
const statusLabel=(s:Service['feeStatus'])=>s==='VERIFIED_CURRENT'?'Tarif vérifié':s==='FREE'?'Gratuit':s==='HISTORICAL'?'Tarif historique — paiement bloqué':'Tarif à confirmer — paiement bloqué';

export default function AdministrativeServicesPage({currentUser}:{currentUser?:any}) {
 const [ministry,setMinistry]=useState('TOUS'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Service|null>(null);
 const [draft,setDraft]=useState<any>(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const start=async()=>{if(!selected)return;setBusy(true);try{const d=await createAdministrativeApplication(selected,currentUser,{});setDraft(d);setNotice('Brouillon créé. Ajoutez les pièces puis soumettez.');}catch(e:any){setNotice(e?.message||'Création impossible');}finally{setBusy(false)}};
 const addFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!draft)return;setBusy(true);try{await uploadAdministrativeFile(draft.id,file);setNotice('Pièce jointe enregistrée dans le stockage privé.');}catch(err:any){setNotice(err?.message||'Téléversement impossible');}finally{setBusy(false)}};
 const submit=async()=>{if(!draft)return;setBusy(true);try{const d=await submitAdministrativeApplication(draft.id);setDraft(d);setNotice('Demande soumise et en attente de traitement.');}catch(err:any){setNotice(err?.message||'Soumission impossible');}finally{setBusy(false)}};
 const rows=useMemo(()=>SERVICES.filter(s=>(ministry==='TOUS'||s.ministry===ministry)&&(!query||[s.name,s.code,s.ministry].join(' ').toLowerCase().includes(query.toLowerCase()))),[ministry,query]);
 return <div className="p-4 sm:p-6 lg:p-8 space-y-6">
  <div className="rounded-3xl bg-[#1F4A59] text-white p-6 shadow-lg"><div className="flex items-center gap-3"><ShieldCheck className="w-8 h-8 text-emerald-300"/><div><h1 className="text-2xl font-black">Démarches administratives</h1><p className="text-slate-200 text-sm">Guichet numérique EDUCO — demandes, suivi, paiement réglementé et documents officiels.</p></div></div></div>
  <div className="grid md:grid-cols-3 gap-3">{[['Démarches disponibles',SERVICES.length,FileText],['Paiements protégés','Tarif vérifié requis',WalletCards],['Traçabilité','Dossier + document',Clock]].map(([t,v,I]:any)=><div className="bg-white rounded-2xl border p-4 flex gap-3 items-center"><I className="w-6 h-6 text-[#1F4A59]"/><div><div className="text-xs text-slate-500 font-bold">{t}</div><div className="font-black text-slate-800">{v}</div></div></div>)}</div>
  <div className="bg-white rounded-2xl border p-4 flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une démarche..." className="w-full pl-10 pr-3 py-2.5 border rounded-xl"/></div><select value={ministry} onChange={e=>setMinistry(e.target.value)} className="border rounded-xl px-3 py-2.5">{['TOUS','MEPSA','METP','MES','MFP'].map(x=><option>{x}</option>)}</select></div>
  <div className="grid lg:grid-cols-2 gap-4">{rows.map(s=><button key={s.code} onClick={()=>setSelected(s)} className="text-left bg-white border rounded-2xl p-5 hover:shadow-md transition"><div className="flex justify-between gap-3"><span className="text-xs font-black text-[#1F4A59]">{s.ministry} · {s.code}</span><span className="text-[10px] font-bold rounded-full bg-amber-50 text-amber-800 px-2 py-1">{statusLabel(s.feeStatus)}</span></div><h2 className="font-black text-slate-900 mt-2">{s.name}</h2><p className="text-sm text-slate-500 mt-1">{s.audience} · {s.result}</p><p className="text-xs text-slate-400 mt-3">Base juridique : {s.legal}</p></button>)}</div>
  {selected&&<div className="fixed inset-0 z-[100] bg-slate-950/60 flex items-end sm:items-center justify-center p-4" onClick={()=>setSelected(null)}><div className="bg-white rounded-3xl p-6 max-w-xl w-full" onClick={e=>e.stopPropagation()}><div className="text-xs font-black text-[#1F4A59]">{selected.ministry} · {selected.code}</div><h2 className="text-xl font-black mt-2">{selected.name}</h2><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm space-y-2"><p><b>Demandeur :</b> {selected.audience}</p><p><b>Document final :</b> {selected.result}</p><p><b>Tarif :</b> {statusLabel(selected.feeStatus)}</p><p><b>Référence :</b> {selected.legal}</p></div><div className="mt-5 p-3 rounded-xl bg-amber-50 text-amber-900 text-sm">Le paiement reste désactivé tant qu'un tarif actuellement applicable et son circuit de perception officiel ne sont pas validés.</div><div className="flex gap-2 mt-5"><button onClick={()=>setSelected(null)} className="px-4 py-2.5 rounded-xl border font-bold">Fermer</button><button onClick={start} disabled={busy} className="flex-1 px-4 py-2.5 rounded-xl bg-[#1F4A59] text-white font-black disabled:opacity-50">Préparer la demande</button>{draft&&<div className="mt-5 border-t pt-5 space-y-3"><div className="flex items-center gap-2 font-black"><FolderOpen className="w-5 h-5"/>Dossier {draft.id.slice(0,8)}</div><label className="flex items-center justify-center gap-2 border-2 border-dashed rounded-xl p-4 cursor-pointer"><UploadCloud className="w-5 h-5"/>Ajouter une pièce justificative<input type="file" className="hidden" onChange={addFile}/></label><button onClick={submit} disabled={busy||draft.status!=='DRAFT'} className="w-full flex items-center justify-center gap-2 rounded-xl bg-emerald-600 text-white font-black py-3 disabled:opacity-50"><Send className="w-4 h-4"/>Soumettre officiellement</button></div>}{notice&&<p className="mt-3 text-sm font-semibold text-slate-600">{notice}</p>}</div></div></div>}
 </div>;
}
