create table if not exists public.administrative_catalog_change_requests (
  id uuid primary key default gen_random_uuid(),
  service_code text not null references public.administrative_services(code) on delete cascade,
  ministry text not null,
  status text not null default 'DRAFT'
    check (status in ('DRAFT','SUBMITTED','CONTROL_APPROVED','APPLIED','REJECTED','CANCELLED')),
  version_base integer not null,
  before_snapshot jsonb not null,
  proposed_service jsonb not null,
  proposed_form_fields jsonb not null default '[]'::jsonb,
  proposed_required_documents jsonb not null default '[]'::jsonb,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,
  control_approved_by uuid references auth.users(id),
  control_approved_at timestamptz,
  final_approved_by uuid references auth.users(id),
  final_approved_at timestamptz,
  rejected_by uuid references auth.users(id),
  rejection_note text,
  applied_at timestamptz
);
alter table public.administrative_catalog_change_requests enable row level security;
revoke all on public.administrative_catalog_change_requests from anon,authenticated;

create unique index if not exists administrative_catalog_one_open_request_per_service
on public.administrative_catalog_change_requests(service_code)
where status in ('DRAFT','SUBMITTED','CONTROL_APPROVED');

create index if not exists administrative_catalog_change_requests_ministry_idx
on public.administrative_catalog_change_requests(ministry,status,created_at desc);

create table if not exists public.administrative_catalog_change_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.administrative_catalog_change_requests(id) on delete cascade,
  service_code text not null,
  ministry text not null,
  action text not null check (action in (
    'DRAFT_CREATED','DRAFT_UPDATED','SUBMITTED','CONTROL_APPROVED',
    'FINAL_APPROVED','REJECTED','CANCELLED','APPLIED'
  )),
  actor_uid uuid not null references auth.users(id),
  note text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.administrative_catalog_change_events enable row level security;
revoke all on public.administrative_catalog_change_events from anon,authenticated;

create index if not exists administrative_catalog_change_events_request_idx
on public.administrative_catalog_change_events(request_id,created_at);

create or replace function private.catalog_actor_role_secure(p_ministry text)
returns text
language sql
security definer
set search_path=''
stable
as $$
 select upper(replace(replace(trim(u.role),' ','_'),'-','_'))
 from public.users u
 join public.administrative_government_accounts g on g.user_uid=auth.uid()
 where u.uid=auth.uid()::text
   and g.active
   and g.ministry=upper(trim(p_ministry))
   and lower(coalesce(u.status,'actif')) not in ('inactif','inactive','suspendu','suspended')
 limit 1
$$;
revoke all on function private.catalog_actor_role_secure(text) from public,anon;
grant execute on function private.catalog_actor_role_secure(text) to authenticated;

create or replace function private.can_edit_catalog_secure(p_ministry text)
returns boolean
language plpgsql
security definer
set search_path=''
stable
as $$
declare r text; m text:=upper(trim(p_ministry));
begin
  if auth.uid() is null then return false; end if;
  r:=private.catalog_actor_role_secure(m);
  if r is null then return false; end if;
  return r in (
    m||'_DIRECTEUR',m||'_DG',m||'_DIRECTEUR_GENERAL',m||'_FINANCE',
    m||'_SECRETAIRE_GENERAL',m||'_CABINET',m||'_MINISTRE'
  );
end $$;
revoke all on function private.can_edit_catalog_secure(text) from public,anon;
grant execute on function private.can_edit_catalog_secure(text) to authenticated;

create or replace function private.can_control_catalog_secure(p_ministry text)
returns boolean
language plpgsql
security definer
set search_path=''
stable
as $$
declare r text; m text:=upper(trim(p_ministry));
begin
  if auth.uid() is null then return false; end if;
  r:=private.catalog_actor_role_secure(m);
  if r is null then return false; end if;
  return r in (
    m||'_DIRECTEUR',m||'_DG',m||'_DIRECTEUR_GENERAL',m||'_FINANCE',
    m||'_SECRETAIRE_GENERAL',m||'_CABINET',m||'_MINISTRE'
  );
end $$;
revoke all on function private.can_control_catalog_secure(text) from public,anon;
grant execute on function private.can_control_catalog_secure(text) to authenticated;

create or replace function private.can_final_approve_catalog_secure(p_ministry text)
returns boolean
language plpgsql
security definer
set search_path=''
stable
as $$
declare r text; m text:=upper(trim(p_ministry));
begin
  if auth.uid() is null then return false; end if;
  r:=private.catalog_actor_role_secure(m);
  if r is null then return false; end if;
  return r in (
    m||'_DG',m||'_DIRECTEUR_GENERAL',m||'_SECRETAIRE_GENERAL',
    m||'_CABINET',m||'_MINISTRE'
  );
end $$;
revoke all on function private.can_final_approve_catalog_secure(text) from public,anon;
grant execute on function private.can_final_approve_catalog_secure(text) to authenticated;

create or replace function private.catalog_service_snapshot_secure(p_service_code text)
returns jsonb
language sql
security definer
set search_path=''
stable
as $$
 select jsonb_build_object(
   'service', to_jsonb(s),
   'form_fields', coalesce((
     select jsonb_agg(to_jsonb(f) order by f.sort_order,f.field_key)
     from public.administrative_service_form_fields f
     where f.service_code=s.code
   ),'[]'::jsonb),
   'required_documents', coalesce((
     select jsonb_agg(to_jsonb(d) order by d.sort_order,d.document_code)
     from public.administrative_service_required_documents d
     where d.service_code=s.code
   ),'[]'::jsonb)
 )
 from public.administrative_services s
 where s.code=p_service_code
 limit 1
$$;
revoke all on function private.catalog_service_snapshot_secure(text) from public,anon;
grant execute on function private.catalog_service_snapshot_secure(text) to authenticated;

create or replace function private.validate_catalog_proposal_secure(
  p_ministry text,
  p_service jsonb,
  p_fields jsonb,
  p_documents jsonb
)
returns boolean
language plpgsql
security definer
set search_path=''
stable
as $$
declare
  legal_status text:=upper(coalesce(p_service->>'legal_status',''));
  fee_status text:=upper(coalesce(p_service->>'fee_status',''));
  publication_status text:=upper(coalesce(p_service->>'publication_status',''));
  requirements_status text:=upper(coalesce(p_service->>'requirements_status',''));
  payment_enabled boolean:=coalesce((p_service->>'payment_enabled')::boolean,false);
  fee_amount numeric;
  duplicate_count integer;
begin
  if jsonb_typeof(p_service)<>'object' or jsonb_typeof(p_fields)<>'array' or jsonb_typeof(p_documents)<>'array' then
    raise exception 'Proposition de catalogue invalide';
  end if;

  if legal_status not in ('VERIFIED','TO_VERIFY','OBSOLETE') then raise exception 'Statut juridique invalide'; end if;
  if fee_status not in ('VERIFIED_CURRENT','HISTORICAL','TO_VERIFY','FREE') then raise exception 'Statut tarifaire invalide'; end if;
  if publication_status not in ('DRAFT','LEGAL_REVIEW','MINISTRY_APPROVED','PUBLISHED','SUSPENDED') then raise exception 'Statut de publication invalide'; end if;
  if requirements_status not in ('TO_VERIFY','VERIFIED','SUSPENDED') then raise exception 'Statut des exigences invalide'; end if;

  if nullif(trim(coalesce(p_service->>'fee_amount','')),'') is not null then
    fee_amount:=(p_service->>'fee_amount')::numeric;
    if fee_amount<0 then raise exception 'Le tarif ne peut pas être négatif'; end if;
  end if;

  if legal_status='VERIFIED' and nullif(trim(coalesce(p_service->>'legal_reference','')),'') is null then
    raise exception 'Une référence juridique est requise pour un statut VERIFIED';
  end if;

  select count(*)-count(distinct x->>'field_key') into duplicate_count
  from jsonb_array_elements(p_fields) x;
  if duplicate_count>0 then raise exception 'Clés de formulaire dupliquées'; end if;

  if exists(
    select 1 from jsonb_array_elements(p_fields) x
    where coalesce(x->>'field_key','') !~ '^[a-z][a-z0-9_]{1,63}$'
       or coalesce(x->>'input_type','') not in ('text','email','tel','date','textarea','select','number')
       or nullif(trim(coalesce(x->>'label','')),'') is null
  ) then raise exception 'Définition de champ de formulaire invalide'; end if;

  select count(*)-count(distinct x->>'document_code') into duplicate_count
  from jsonb_array_elements(p_documents) x;
  if duplicate_count>0 then raise exception 'Codes de pièces dupliqués'; end if;

  if exists(
    select 1 from jsonb_array_elements(p_documents) x
    where coalesce(x->>'document_code','') !~ '^[A-Z0-9_-]{2,64}$'
       or nullif(trim(coalesce(x->>'label','')),'') is null
       or coalesce((x->>'max_size_bytes')::bigint,10485760) not between 1 and 52428800
  ) then raise exception 'Définition de pièce justificative invalide'; end if;

  if requirements_status='VERIFIED' then
    if exists(
      select 1 from jsonb_array_elements(p_fields) x
      where coalesce((x->>'active')::boolean,true)
        and coalesce((x->>'required')::boolean,false)
        and not coalesce((x->>'verified')::boolean,false)
    ) then raise exception 'Tous les champs obligatoires doivent être vérifiés'; end if;

    if exists(
      select 1 from jsonb_array_elements(p_documents) x
      where coalesce((x->>'active')::boolean,true)
        and coalesce((x->>'required')::boolean,false)
        and not coalesce((x->>'verified')::boolean,false)
    ) then raise exception 'Toutes les pièces obligatoires doivent être vérifiées'; end if;
  end if;

  if fee_status='FREE' and payment_enabled then raise exception 'Une démarche gratuite ne peut pas activer un paiement'; end if;
  if payment_enabled and (fee_status<>'VERIFIED_CURRENT' or fee_amount is null) then
    raise exception 'Paiement impossible sans tarif courant vérifié';
  end if;

  if publication_status='PUBLISHED' then
    if legal_status<>'VERIFIED' then raise exception 'Publication impossible sans validation juridique'; end if;
    if requirements_status<>'VERIFIED' then raise exception 'Publication impossible sans validation des exigences'; end if;
    if nullif(trim(coalesce(p_service->>'output_document','')),'') is null then
      raise exception 'Le document final doit être défini avant publication';
    end if;
  end if;

  return true;
end $$;
revoke all on function private.validate_catalog_proposal_secure(text,jsonb,jsonb,jsonb) from public,anon;
grant execute on function private.validate_catalog_proposal_secure(text,jsonb,jsonb,jsonb) to authenticated;

create or replace function private.save_catalog_change_request_secure(
  p_request_id uuid,
  p_service_code text,
  p_proposed_service jsonb,
  p_form_fields jsonb,
  p_required_documents jsonb
)
returns public.administrative_catalog_change_requests
language plpgsql
security definer
set search_path=''
as $$
declare
  s public.administrative_services;
  r public.administrative_catalog_change_requests;
  snap jsonb;
begin
  if auth.uid() is null then raise exception 'Authentification requise'; end if;
  select * into s from public.administrative_services where code=p_service_code;
  if s.code is null then raise exception 'Démarche introuvable'; end if;
  if not private.can_edit_catalog_secure(s.ministry) then raise exception 'Accès non autorisé'; end if;

  perform private.validate_catalog_proposal_secure(s.ministry,p_proposed_service,p_form_fields,p_required_documents);
  snap:=private.catalog_service_snapshot_secure(s.code);

  if p_request_id is null then
    if exists(
      select 1 from public.administrative_catalog_change_requests x
      where x.service_code=s.code and x.status in ('DRAFT','SUBMITTED','CONTROL_APPROVED')
    ) then raise exception 'Une proposition est déjà ouverte pour cette démarche'; end if;

    insert into public.administrative_catalog_change_requests(
      service_code,ministry,status,version_base,before_snapshot,proposed_service,
      proposed_form_fields,proposed_required_documents,created_by
    ) values(
      s.code,s.ministry,'DRAFT',s.form_version,snap,p_proposed_service,
      p_form_fields,p_required_documents,auth.uid()
    ) returning * into r;

    insert into public.administrative_catalog_change_events(
      request_id,service_code,ministry,action,actor_uid,payload
    ) values(r.id,s.code,s.ministry,'DRAFT_CREATED',auth.uid(),
      jsonb_build_object('version_base',s.form_version));
  else
    select * into r from public.administrative_catalog_change_requests where id=p_request_id for update;
    if r.id is null or r.service_code<>s.code then raise exception 'Proposition introuvable'; end if;
    if r.status<>'DRAFT' then raise exception 'Seul un brouillon peut être modifié'; end if;
    if r.created_by<>auth.uid() then raise exception 'Seul le créateur peut modifier ce brouillon'; end if;

    update public.administrative_catalog_change_requests
    set proposed_service=p_proposed_service,
        proposed_form_fields=p_form_fields,
        proposed_required_documents=p_required_documents,
        updated_at=now()
    where id=r.id returning * into r;

    insert into public.administrative_catalog_change_events(
      request_id,service_code,ministry,action,actor_uid
    ) values(r.id,s.code,s.ministry,'DRAFT_UPDATED',auth.uid());
  end if;
  return r;
end $$;
revoke all on function private.save_catalog_change_request_secure(uuid,text,jsonb,jsonb,jsonb) from public,anon;
grant execute on function private.save_catalog_change_request_secure(uuid,text,jsonb,jsonb,jsonb) to authenticated;

create or replace function public.save_catalog_change_request(
  p_request_id uuid,p_service_code text,p_proposed_service jsonb,p_form_fields jsonb,p_required_documents jsonb
)
returns public.administrative_catalog_change_requests
language sql security invoker set search_path=''
as $$ select private.save_catalog_change_request_secure(p_request_id,p_service_code,p_proposed_service,p_form_fields,p_required_documents) $$;
revoke all on function public.save_catalog_change_request(uuid,text,jsonb,jsonb,jsonb) from public,anon;
grant execute on function public.save_catalog_change_request(uuid,text,jsonb,jsonb,jsonb) to authenticated;

create or replace function private.submit_catalog_change_request_secure(p_request_id uuid)
returns public.administrative_catalog_change_requests
language plpgsql security definer set search_path=''
as $$
declare r public.administrative_catalog_change_requests;
begin
  if auth.uid() is null then raise exception 'Authentification requise'; end if;
  select * into r from public.administrative_catalog_change_requests where id=p_request_id for update;
  if r.id is null then raise exception 'Proposition introuvable'; end if;
  if r.status<>'DRAFT' or r.created_by<>auth.uid() then raise exception 'Brouillon non soumissible'; end if;
  if not private.can_edit_catalog_secure(r.ministry) then raise exception 'Accès non autorisé'; end if;
  perform private.validate_catalog_proposal_secure(r.ministry,r.proposed_service,r.proposed_form_fields,r.proposed_required_documents);

  update public.administrative_catalog_change_requests
  set status='SUBMITTED',submitted_at=now(),updated_at=now()
  where id=r.id returning * into r;

  insert into public.administrative_catalog_change_events(request_id,service_code,ministry,action,actor_uid)
  values(r.id,r.service_code,r.ministry,'SUBMITTED',auth.uid());
  return r;
end $$;
revoke all on function private.submit_catalog_change_request_secure(uuid) from public,anon;
grant execute on function private.submit_catalog_change_request_secure(uuid) to authenticated;

create or replace function public.submit_catalog_change_request(p_request_id uuid)
returns public.administrative_catalog_change_requests
language sql security invoker set search_path=''
as $$ select private.submit_catalog_change_request_secure(p_request_id) $$;
revoke all on function public.submit_catalog_change_request(uuid) from public,anon;
grant execute on function public.submit_catalog_change_request(uuid) to authenticated;

create or replace function private.review_catalog_change_request_secure(
  p_request_id uuid,p_decision text,p_note text default null
)
returns public.administrative_catalog_change_requests
language plpgsql security definer set search_path=''
as $$
declare
  r public.administrative_catalog_change_requests;
  decision text:=upper(trim(p_decision));
begin
  if auth.uid() is null then raise exception 'Authentification requise'; end if;
  select * into r from public.administrative_catalog_change_requests where id=p_request_id for update;
  if r.id is null then raise exception 'Proposition introuvable'; end if;
  if r.status<>'SUBMITTED' then raise exception 'Proposition non disponible pour le premier contrôle'; end if;
  if not private.can_control_catalog_secure(r.ministry) then raise exception 'Accès non autorisé'; end if;
  if r.created_by=auth.uid() then raise exception 'Le créateur ne peut pas effectuer le premier contrôle'; end if;

  if decision='APPROVE' then
    perform private.validate_catalog_proposal_secure(r.ministry,r.proposed_service,r.proposed_form_fields,r.proposed_required_documents);
    update public.administrative_catalog_change_requests
    set status='CONTROL_APPROVED',control_approved_by=auth.uid(),control_approved_at=now(),updated_at=now()
    where id=r.id returning * into r;
    insert into public.administrative_catalog_change_events(request_id,service_code,ministry,action,actor_uid,note)
    values(r.id,r.service_code,r.ministry,'CONTROL_APPROVED',auth.uid(),p_note);
  elsif decision='REJECT' then
    if nullif(trim(coalesce(p_note,'')),'') is null then raise exception 'Un motif de rejet est requis'; end if;
    update public.administrative_catalog_change_requests
    set status='REJECTED',rejected_by=auth.uid(),rejection_note=p_note,updated_at=now()
    where id=r.id returning * into r;
    insert into public.administrative_catalog_change_events(request_id,service_code,ministry,action,actor_uid,note)
    values(r.id,r.service_code,r.ministry,'REJECTED',auth.uid(),p_note);
  else
    raise exception 'Décision invalide';
  end if;
  return r;
end $$;
revoke all on function private.review_catalog_change_request_secure(uuid,text,text) from public,anon;
grant execute on function private.review_catalog_change_request_secure(uuid,text,text) to authenticated;

create or replace function public.review_catalog_change_request(
  p_request_id uuid,p_decision text,p_note text default null
)
returns public.administrative_catalog_change_requests
language sql security invoker set search_path=''
as $$ select private.review_catalog_change_request_secure(p_request_id,p_decision,p_note) $$;
revoke all on function public.review_catalog_change_request(uuid,text,text) from public,anon;
grant execute on function public.review_catalog_change_request(uuid,text,text) to authenticated;

create or replace function private.finalize_catalog_change_request_secure(
  p_request_id uuid,p_decision text,p_note text default null
)
returns public.administrative_catalog_change_requests
language plpgsql security definer set search_path=''
as $$
declare
  r public.administrative_catalog_change_requests;
  s public.administrative_services;
  decision text:=upper(trim(p_decision));
  ps jsonb;
  f jsonb;
  d jsonb;
begin
  if auth.uid() is null then raise exception 'Authentification requise'; end if;
  select * into r from public.administrative_catalog_change_requests where id=p_request_id for update;
  if r.id is null then raise exception 'Proposition introuvable'; end if;
  if r.status<>'CONTROL_APPROVED' then raise exception 'La proposition doit avoir passé le premier contrôle'; end if;
  if not private.can_final_approve_catalog_secure(r.ministry) then raise exception 'Accès final non autorisé'; end if;
  if r.created_by=auth.uid() or r.control_approved_by=auth.uid() then
    raise exception 'Le second contrôle doit être effectué par une troisième personne distincte';
  end if;

  if decision='REJECT' then
    if nullif(trim(coalesce(p_note,'')),'') is null then raise exception 'Un motif de rejet est requis'; end if;
    update public.administrative_catalog_change_requests
    set status='REJECTED',rejected_by=auth.uid(),rejection_note=p_note,updated_at=now()
    where id=r.id returning * into r;
    insert into public.administrative_catalog_change_events(request_id,service_code,ministry,action,actor_uid,note)
    values(r.id,r.service_code,r.ministry,'REJECTED',auth.uid(),p_note);
    return r;
  elsif decision<>'APPROVE' then
    raise exception 'Décision invalide';
  end if;

  select * into s from public.administrative_services where code=r.service_code for update;
  if s.code is null then raise exception 'Démarche introuvable'; end if;
  if s.form_version<>r.version_base then raise exception 'Le catalogue a changé depuis la création de cette proposition'; end if;
  perform private.validate_catalog_proposal_secure(r.ministry,r.proposed_service,r.proposed_form_fields,r.proposed_required_documents);
  ps:=r.proposed_service;

  update public.administrative_services
  set name=coalesce(nullif(trim(ps->>'name'),''),name),
      audience=coalesce(nullif(trim(ps->>'audience'),''),audience),
      competent_direction=nullif(trim(ps->>'competent_direction'),''),
      competent_service=nullif(trim(ps->>'competent_service'),''),
      legal_status=upper(ps->>'legal_status'),
      legal_reference=nullif(trim(ps->>'legal_reference'),''),
      legal_source_url=nullif(trim(ps->>'legal_source_url'),''),
      fee_amount=case when nullif(trim(coalesce(ps->>'fee_amount','')),'') is null then null else (ps->>'fee_amount')::numeric end,
      fee_currency=upper(coalesce(nullif(trim(ps->>'fee_currency'),''),'XAF')),
      fee_status=upper(ps->>'fee_status'),
      publication_status=upper(ps->>'publication_status'),
      requirements_status=upper(ps->>'requirements_status'),
      output_document=nullif(trim(ps->>'output_document'),''),
      payment_enabled=coalesce((ps->>'payment_enabled')::boolean,false),
      form_version=form_version+1,
      updated_at=now()
  where code=s.code;

  delete from public.administrative_service_form_fields where service_code=s.code;
  for f in select value from jsonb_array_elements(r.proposed_form_fields)
  loop
    insert into public.administrative_service_form_fields(
      service_code,field_key,label,input_type,required,verified,options,help_text,sort_order,active
    ) values(
      s.code,f->>'field_key',f->>'label',f->>'input_type',
      coalesce((f->>'required')::boolean,false),coalesce((f->>'verified')::boolean,false),
      coalesce(f->'options','[]'::jsonb),nullif(trim(f->>'help_text'),''),
      coalesce((f->>'sort_order')::integer,0),coalesce((f->>'active')::boolean,true)
    );
  end loop;

  delete from public.administrative_service_required_documents where service_code=s.code;
  for d in select value from jsonb_array_elements(r.proposed_required_documents)
  loop
    insert into public.administrative_service_required_documents(
      service_code,document_code,label,required,verified,conditional_note,
      allowed_mime_types,max_size_bytes,sort_order,active
    ) values(
      s.code,d->>'document_code',d->>'label',
      coalesce((d->>'required')::boolean,true),coalesce((d->>'verified')::boolean,false),
      nullif(trim(d->>'conditional_note'),''),
      coalesce(array(select jsonb_array_elements_text(coalesce(d->'allowed_mime_types','["application/pdf","image/jpeg","image/png"]'::jsonb))),
        array['application/pdf','image/jpeg','image/png']::text[]),
      coalesce((d->>'max_size_bytes')::bigint,10485760),
      coalesce((d->>'sort_order')::integer,0),coalesce((d->>'active')::boolean,true)
    );
  end loop;

  update public.administrative_catalog_change_requests
  set status='APPLIED',final_approved_by=auth.uid(),final_approved_at=now(),applied_at=now(),updated_at=now()
  where id=r.id returning * into r;

  insert into public.administrative_catalog_change_events(
    request_id,service_code,ministry,action,actor_uid,note,payload
  ) values(
    r.id,r.service_code,r.ministry,'FINAL_APPROVED',auth.uid(),p_note,
    jsonb_build_object('new_form_version',s.form_version+1)
  );

  insert into public.administrative_catalog_change_events(
    request_id,service_code,ministry,action,actor_uid,payload
  ) values(
    r.id,r.service_code,r.ministry,'APPLIED',auth.uid(),
    jsonb_build_object('publication_status',upper(ps->>'publication_status'))
  );
  return r;
end $$;
revoke all on function private.finalize_catalog_change_request_secure(uuid,text,text) from public,anon;
grant execute on function private.finalize_catalog_change_request_secure(uuid,text,text) to authenticated;

create or replace function public.finalize_catalog_change_request(
  p_request_id uuid,p_decision text,p_note text default null
)
returns public.administrative_catalog_change_requests
language sql security invoker set search_path=''
as $$ select private.finalize_catalog_change_request_secure(p_request_id,p_decision,p_note) $$;
revoke all on function public.finalize_catalog_change_request(uuid,text,text) from public,anon;
grant execute on function public.finalize_catalog_change_request(uuid,text,text) to authenticated;

create or replace function private.cancel_catalog_change_request_secure(p_request_id uuid)
returns public.administrative_catalog_change_requests
language plpgsql security definer set search_path=''
as $$
declare r public.administrative_catalog_change_requests;
begin
  if auth.uid() is null then raise exception 'Authentification requise'; end if;
  select * into r from public.administrative_catalog_change_requests where id=p_request_id for update;
  if r.id is null or r.status<>'DRAFT' or r.created_by<>auth.uid() then raise exception 'Brouillon non annulable'; end if;
  update public.administrative_catalog_change_requests set status='CANCELLED',updated_at=now()
  where id=r.id returning * into r;
  insert into public.administrative_catalog_change_events(request_id,service_code,ministry,action,actor_uid)
  values(r.id,r.service_code,r.ministry,'CANCELLED',auth.uid());
  return r;
end $$;
revoke all on function private.cancel_catalog_change_request_secure(uuid) from public,anon;
grant execute on function private.cancel_catalog_change_request_secure(uuid) to authenticated;

create or replace function public.cancel_catalog_change_request(p_request_id uuid)
returns public.administrative_catalog_change_requests
language sql security invoker set search_path=''
as $$ select private.cancel_catalog_change_request_secure(p_request_id) $$;
revoke all on function public.cancel_catalog_change_request(uuid) from public,anon;
grant execute on function public.cancel_catalog_change_request(uuid) to authenticated;

create or replace function private.list_catalog_validation_workspace_secure(p_ministry text)
returns table(
  service_code text,ministry text,service_name text,current_snapshot jsonb,active_request jsonb,
  can_edit boolean,can_control boolean,can_final_approve boolean
)
language plpgsql security definer set search_path='' stable
as $$
declare m text:=upper(trim(p_ministry)); allowed boolean;
begin
  allowed:=private.can_edit_catalog_secure(m) or private.can_control_catalog_secure(m) or private.can_final_approve_catalog_secure(m);
  if not allowed then raise exception 'Accès non autorisé'; end if;

  return query
  select
    s.code,s.ministry,s.name,
    private.catalog_service_snapshot_secure(s.code),
    (
      select jsonb_build_object(
        'id',r.id,'status',r.status,'version_base',r.version_base,
        'proposed_service',r.proposed_service,
        'proposed_form_fields',r.proposed_form_fields,
        'proposed_required_documents',r.proposed_required_documents,
        'created_by',r.created_by,'created_at',r.created_at,'submitted_at',r.submitted_at,
        'control_approved_by',r.control_approved_by,'control_approved_at',r.control_approved_at,
        'final_approved_by',r.final_approved_by,'final_approved_at',r.final_approved_at,
        'rejection_note',r.rejection_note
      )
      from public.administrative_catalog_change_requests r
      where r.service_code=s.code and r.status in ('DRAFT','SUBMITTED','CONTROL_APPROVED')
      order by r.created_at desc limit 1
    ),
    private.can_edit_catalog_secure(m),
    private.can_control_catalog_secure(m),
    private.can_final_approve_catalog_secure(m)
  from public.administrative_services s
  where s.ministry=m
  order by s.name;
end $$;
revoke all on function private.list_catalog_validation_workspace_secure(text) from public,anon;
grant execute on function private.list_catalog_validation_workspace_secure(text) to authenticated;

create or replace function public.list_catalog_validation_workspace(p_ministry text)
returns table(
  service_code text,ministry text,service_name text,current_snapshot jsonb,active_request jsonb,
  can_edit boolean,can_control boolean,can_final_approve boolean
)
language sql security invoker set search_path='' stable
as $$ select * from private.list_catalog_validation_workspace_secure(p_ministry) $$;
revoke all on function public.list_catalog_validation_workspace(text) from public,anon;
grant execute on function public.list_catalog_validation_workspace(text) to authenticated;

create or replace function private.list_catalog_change_history_secure(p_service_code text)
returns table(
  event_id bigint,request_id uuid,action text,note text,created_at timestamptz,
  actor_uid uuid,actor_name text,request_status text
)
language plpgsql security definer set search_path='' stable
as $$
declare s public.administrative_services;
begin
  select * into s from public.administrative_services where code=p_service_code;
  if s.code is null then raise exception 'Démarche introuvable'; end if;
  if not (private.can_edit_catalog_secure(s.ministry) or private.can_control_catalog_secure(s.ministry) or private.can_final_approve_catalog_secure(s.ministry)) then
    raise exception 'Accès non autorisé';
  end if;

  return query
  select e.id,e.request_id,e.action,e.note,e.created_at,e.actor_uid,u.name,r.status
  from public.administrative_catalog_change_events e
  join public.administrative_catalog_change_requests r on r.id=e.request_id
  left join public.users u on u.uid=e.actor_uid::text
  where e.service_code=p_service_code
  order by e.created_at desc
  limit 100;
end $$;
revoke all on function private.list_catalog_change_history_secure(text) from public,anon;
grant execute on function private.list_catalog_change_history_secure(text) to authenticated;

create or replace function public.list_catalog_change_history(p_service_code text)
returns table(
  event_id bigint,request_id uuid,action text,note text,created_at timestamptz,
  actor_uid uuid,actor_name text,request_status text
)
language sql security invoker set search_path='' stable
as $$ select * from private.list_catalog_change_history_secure(p_service_code) $$;
revoke all on function public.list_catalog_change_history(text) from public,anon;
grant execute on function public.list_catalog_change_history(text) to authenticated;

revoke insert,update,delete on public.administrative_services from anon,authenticated;
revoke insert,update,delete on public.administrative_service_form_fields from anon,authenticated;
revoke insert,update,delete on public.administrative_service_required_documents from anon,authenticated;
